export interface AppUser {
  id: string;
  name: string;
  email: string;
  phone: string;
  location: string;
  dateJoined: string; // ISO format: YYYY-MM-DD
  lastActivity: string;
  totalOrders: number;
  status: "Active" | "New" | "Inactive";
  avatarInitials: string;
  avatarColorBg: string;
  avatarColorText: string;
}

const INITIAL_APP_USERS: AppUser[] = [
  {
    id: "1",
    name: "Amara Nwosu",
    email: "amara.n@example.com",
    phone: "+234 802 123 4567",
    location: "Lagos, Nigeria",
    dateJoined: "2023-10-12",
    lastActivity: "2 mins ago",
    totalOrders: 14,
    status: "Active",
    avatarInitials: "AN",
    avatarColorBg: "bg-[#FFF0F2]",
    avatarColorText: "text-[#B31046]",
  },
  {
    id: "2",
    name: "Kofi Osei",
    email: "kofi.osei@ghana.com",
    phone: "+233 24 555 0192",
    location: "Accra, Ghana",
    dateJoined: "2023-11-01",
    lastActivity: "Just now",
    totalOrders: 3,
    status: "New",
    avatarInitials: "KO",
    avatarColorBg: "bg-blue-50",
    avatarColorText: "text-blue-600",
  },
  {
    id: "3",
    name: "Chioma Jide",
    email: "chioma.j@bentlab.co",
    phone: "+234 703 987 6543",
    location: "Abuja, Nigeria",
    dateJoined: "2023-01-15",
    lastActivity: "5 days ago",
    totalOrders: 28,
    status: "Inactive",
    avatarInitials: "CJ",
    avatarColorBg: "bg-zinc-100",
    avatarColorText: "text-zinc-600",
  },
  {
    id: "4",
    name: "Elena Smith",
    email: "elena.smith@global.net",
    phone: "+254 712 345 678",
    location: "Nairobi, Kenya",
    dateJoined: "2023-08-22",
    lastActivity: "12 hours ago",
    totalOrders: 52,
    status: "Active",
    avatarInitials: "ES",
    avatarColorBg: "bg-emerald-50",
    avatarColorText: "text-emerald-700",
  },
  {
    id: "5",
    name: "Babajide Mike",
    email: "b.mike@domain.ng",
    phone: "+234 901 222 3333",
    location: "Port Harcourt, NG",
    dateJoined: "2023-12-05",
    lastActivity: "45 mins ago",
    totalOrders: 1,
    status: "New",
    avatarInitials: "BM",
    avatarColorBg: "bg-amber-50",
    avatarColorText: "text-amber-700",
  },
  {
    id: "6",
    name: "Kwame Nkrumah",
    email: "k.nkrumah@heritage.com",
    phone: "+233 20 888 7777",
    location: "Kumasi, Ghana",
    dateJoined: "2023-09-14",
    lastActivity: "3 hours ago",
    totalOrders: 8,
    status: "Active",
    avatarInitials: "KN",
    avatarColorBg: "bg-[#FFF0F2]",
    avatarColorText: "text-[#B31046]",
  },
  {
    id: "7",
    name: "Fatima Yusuf",
    email: "f.yusuf@kano.ng",
    phone: "+234 809 333 4444",
    location: "Kano, Nigeria",
    dateJoined: "2023-05-18",
    lastActivity: "Yesterday",
    totalOrders: 19,
    status: "Active",
    avatarInitials: "FY",
    avatarColorBg: "bg-emerald-50",
    avatarColorText: "text-emerald-700",
  },
  {
    id: "8",
    name: "Jabari Mwangi",
    email: "jabari@safari.co.ke",
    phone: "+254 722 999 111",
    location: "Mombasa, Kenya",
    dateJoined: "2023-11-20",
    lastActivity: "Just now",
    totalOrders: 2,
    status: "New",
    avatarInitials: "JM",
    avatarColorBg: "bg-blue-50",
    avatarColorText: "text-blue-600",
  },
  {
    id: "9",
    name: "Aisha Bello",
    email: "aisha.b@kaduna.ng",
    phone: "+234 812 555 6666",
    location: "Kaduna, Nigeria",
    dateJoined: "2023-02-10",
    lastActivity: "4 days ago",
    totalOrders: 0,
    status: "Inactive",
    avatarInitials: "AB",
    avatarColorBg: "bg-zinc-100",
    avatarColorText: "text-zinc-600",
  },
  {
    id: "10",
    name: "Tunde Folawiyo",
    email: "tfolawiyo@yinka.com",
    phone: "+234 803 777 8888",
    location: "Ibadan, Nigeria",
    dateJoined: "2023-07-30",
    lastActivity: "18 mins ago",
    totalOrders: 31,
    status: "Active",
    avatarInitials: "TF",
    avatarColorBg: "bg-amber-50",
    avatarColorText: "text-amber-700",
  },
  {
    id: "11",
    name: "Efe Odegba",
    email: "efe.odegba@delta.ng",
    phone: "+234 815 444 3322",
    location: "Warri, Nigeria",
    dateJoined: "2023-11-28",
    lastActivity: "Just now",
    totalOrders: 0,
    status: "New",
    avatarInitials: "EO",
    avatarColorBg: "bg-blue-50",
    avatarColorText: "text-blue-600",
  },
  {
    id: "12",
    name: "Naomi Wanjiku",
    email: "naomi.w@kenya.net",
    phone: "+254 701 444 555",
    location: "Kisumu, Kenya",
    dateJoined: "2023-04-05",
    lastActivity: "3 days ago",
    totalOrders: 15,
    status: "Active",
    avatarInitials: "NW",
    avatarColorBg: "bg-emerald-50",
    avatarColorText: "text-emerald-700",
  },
  {
    id: "13",
    name: "Ekow Mensah",
    email: "ekow.m@ghana.com",
    phone: "+233 26 777 9900",
    location: "Takoradi, Ghana",
    dateJoined: "2023-03-25",
    lastActivity: "1 week ago",
    totalOrders: 7,
    status: "Inactive",
    avatarInitials: "EM",
    avatarColorBg: "bg-zinc-100",
    avatarColorText: "text-zinc-600",
  },
  {
    id: "14",
    name: "Zola Dlamini",
    email: "zola.d@southafrica.net",
    phone: "+27 82 555 1234",
    location: "Johannesburg, SA",
    dateJoined: "2023-08-10",
    lastActivity: "10 mins ago",
    totalOrders: 42,
    status: "Active",
    avatarInitials: "ZD",
    avatarColorBg: "bg-[#FFF0F2]",
    avatarColorText: "text-[#B31046]",
  },
  {
    id: "15",
    name: "Ngozi Adebayo",
    email: "ngozi@adebayo.io",
    phone: "+234 802 999 8888",
    location: "Lagos, Nigeria",
    dateJoined: "2023-12-01",
    lastActivity: "Just now",
    totalOrders: 4,
    status: "New",
    avatarInitials: "NA",
    avatarColorBg: "bg-blue-50",
    avatarColorText: "text-blue-600",
  },
  {
    id: "16",
    name: "Simba Ndlovu",
    email: "simba@harare.zw",
    phone: "+263 77 123 4567",
    location: "Harare, Zimbabwe",
    dateJoined: "2023-06-15",
    lastActivity: "2 hours ago",
    totalOrders: 11,
    status: "Active",
    avatarInitials: "SN",
    avatarColorBg: "bg-emerald-50",
    avatarColorText: "text-emerald-700",
  },
  {
    id: "17",
    name: "Sarah Geller",
    email: "s.geller@global.net",
    phone: "+1 212 555 0199",
    location: "New York, USA",
    dateJoined: "2023-12-03",
    lastActivity: "5 hours ago",
    totalOrders: 1,
    status: "New",
    avatarInitials: "SG",
    avatarColorBg: "bg-blue-50",
    avatarColorText: "text-blue-600",
  },
  {
    id: "18",
    name: "Chinedu Okechukwu",
    email: "chinedu.o@eastern.ng",
    phone: "+234 813 444 8888",
    location: "Enugu, Nigeria",
    dateJoined: "2023-01-20",
    lastActivity: "3 weeks ago",
    totalOrders: 35,
    status: "Inactive",
    avatarInitials: "CO",
    avatarColorBg: "bg-zinc-100",
    avatarColorText: "text-zinc-600",
  },
  {
    id: "19",
    name: "Lydia Kemunto",
    email: "lydia@kemunto.com",
    phone: "+254 711 222 333",
    location: "Nakuru, Kenya",
    dateJoined: "2023-10-05",
    lastActivity: "1 day ago",
    totalOrders: 23,
    status: "Active",
    avatarInitials: "LK",
    avatarColorBg: "bg-amber-50",
    avatarColorText: "text-amber-700",
  },
  {
    id: "20",
    name: "Emeka Obi",
    email: "emeka.obi@nigeria.ng",
    phone: "+234 807 111 2222",
    location: "Asaba, Nigeria",
    dateJoined: "2023-11-25",
    lastActivity: "6 mins ago",
    totalOrders: 5,
    status: "Active",
    avatarInitials: "EO",
    avatarColorBg: "bg-[#FFF0F2]",
    avatarColorText: "text-[#B31046]",
  },
  {
    id: "21",
    name: "Dela Sowah",
    email: "dela.sowah@ghana.com",
    phone: "+233 24 111 2233",
    location: "Tema, Ghana",
    dateJoined: "2023-12-04",
    lastActivity: "42 mins ago",
    totalOrders: 1,
    status: "New",
    avatarInitials: "DS",
    avatarColorBg: "bg-blue-50",
    avatarColorText: "text-blue-600",
  },
  {
    id: "22",
    name: "Moussa Diop",
    email: "moussa.diop@senegal.sn",
    phone: "+221 77 555 4433",
    location: "Dakar, Senegal",
    dateJoined: "2023-08-30",
    lastActivity: "2 days ago",
    totalOrders: 12,
    status: "Active",
    avatarInitials: "MD",
    avatarColorBg: "bg-emerald-50",
    avatarColorText: "text-emerald-700",
  },
  {
    id: "23",
    name: "Abdi Ibrahim",
    email: "abdi@somalia.net",
    phone: "+252 61 555 9999",
    location: "Mogadishu, Somalia",
    dateJoined: "2023-02-18",
    lastActivity: "1 month ago",
    totalOrders: 9,
    status: "Inactive",
    avatarInitials: "AI",
    avatarColorBg: "bg-zinc-100",
    avatarColorText: "text-zinc-600",
  },
  {
    id: "24",
    name: "Oluwaseun Ajayi",
    email: "oluwaseun@ajayi.org",
    phone: "+234 810 999 1111",
    location: "Abeokuta, Nigeria",
    dateJoined: "2023-10-18",
    lastActivity: "Just now",
    totalOrders: 16,
    status: "Active",
    avatarInitials: "OA",
    avatarColorBg: "bg-[#FFF0F2]",
    avatarColorText: "text-[#B31046]",
  },
  {
    id: "25",
    name: "Farah Ghedi",
    email: "farah@ghedi.so",
    phone: "+252 90 222 1111",
    location: "Garowe, Somalia",
    dateJoined: "2023-12-06",
    lastActivity: "1 min ago",
    totalOrders: 0,
    status: "New",
    avatarInitials: "FG",
    avatarColorBg: "bg-blue-50",
    avatarColorText: "text-blue-600",
  }
];

export function getStoredAppUsers(): AppUser[] {
  if (typeof window === "undefined") return INITIAL_APP_USERS;
  try {
    const data = localStorage.getItem("bentlab_app_users");
    if (data) {
      return JSON.parse(data);
    }
  } catch (e) {
    console.error("Error reading stored app users", e);
  }
  return INITIAL_APP_USERS;
}

export function saveStoredAppUsers(users: AppUser[]): void {
  if (typeof window === "undefined") return;
  try {
    localStorage.setItem("bentlab_app_users", JSON.stringify(users));
  } catch (e) {
    console.error("Error saving app users", e);
  }
}
